import type { NextPage } from 'next';
import Head from 'next/head';
import { useTheme } from 'next-themes';
const Home: NextPage = () => {
  const { theme, setTheme } = useTheme();
  return (
    <div className="app">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      The current theme is: {theme}
      <button onClick={() => setTheme('light')}>Light Mode</button>
      <button onClick={() => setTheme('dark')}>Dark Mode</button>
    </div>
  );
};

export default Home;
